version: "3.9"
services: 
  backend: 
    container_name: backend
    build: 
      context: ./phone-validator
    ports: 
      - '8080:8080'
  frontend:
    build: 
      context: ./phone-validator-frontend/
    ports: 
      - '80:80'